import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignIn, SignedIn, SignedOut, UserButton, } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Option Data Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <header className="flex justify-between items-center p-4">
            <img 
              src="/Group 137.png" 
              alt="Your Image" 
              className="h-20 w-25" 
            />
            <div className="relative" style={{ top: '-1rem' }}>
              <UserButton showName />
            </div>
          </header>
          <main className="flex justify-center items-center min-h-screen">
            <SignedOut>
              <SignIn routing="hash" />
            </SignedOut>
            <SignedIn>
              {children}
            </SignedIn>
            
          </main>
        </body>
      </html>      
    </ClerkProvider>

  );
}

